//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students
    {
        public Students()
        {
            this.Quiz_Students = new HashSet<Quiz_Students>();
            this.Subject = new HashSet<Subject>();
        }
    
        public int Id { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string gender { get; set; }
        public Nullable<int> age { get; set; }
        public string phoneNumber { get; set; }
    
        public virtual ICollection<Quiz_Students> Quiz_Students { get; set; }
        public virtual ICollection<Subject> Subject { get; set; }
    }
}
