//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject
    {
        public Subject()
        {
            this.Quiz = new HashSet<Quiz>();
            this.Students = new HashSet<Students>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int year { get; set; }
    
        public virtual ICollection<Quiz> Quiz { get; set; }
        public virtual ICollection<Students> Students { get; set; }
    }
}
